### ISSUE TITLE
Auth token cannot serve the request

### ISSUE THREAD

**Issue by ralbert05** [stalker314314/DocumentDBCpp#12]
Hello, I'm getting the following error when trying to grab a database from cosmosdb. 

"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get\ndbs\ndbs/TestDatabase\nmon, 11 jun 2018 20:34:21 gmt\n\n'\r\nActivityId: d3182644-c348-4913-90fe-7200a3ae34fb, Microsoft.Azure.Documents.Common/2.0.0.0"

I can create DBs and collections, but cannot seem to get the DBs even after just creating them.

`client.CreateDatabase(dbresourceid);
 client.GetDatabase(dbresourceid).get();
 shared_ptr<Database> db = client.GetDatabase(dbresourceid);`

Let me know if I am doing something wrong or if this is an issue.

**Comment by stalker314314** [comment]
So, there is a difference between database id (name) and its resource id. When you create DB, you create it with name. When you want to get it with GetDatabase, you need to use resourcedb. You get resourcedb only when DB is created. I would suggest you to try that first. For example, look at [tests](https://github.com/stalker314314/DocumentDBCpp/blob/master/test/test.cpp), in `test_databases` function, there is example there. Hope it helps. I will keep this issue open until we figure out is it a API usage issue, or some real issue:)

edit: added link to tests

**Comment by ralbert05** [comment]
Okay, so almost definitely user error, thank you for following up. So to _get_ a database, I will need to have the resourceId. Is this somewhere accessible in Azure or do I need to get it in the API? I understand in tests we get the database from creating it, and then later when we want to get the database, we use that database and its resourceId. 

I'm new to Azure and HttpRequests in general, so thanks for helping out.

**Comment by stalker314314** [comment]
No problem:)

I think it is available both in Azure and in API. I was checking just now [this link](https://docs.microsoft.com/en-us/rest/api/cosmos-db/get-a-database) and it seems that API changed, so that you can get DB by its id (before, it was possible only by using resourceid), so that must have been changed. Maybe it is time to refresh this project a bit:) As long as it is working for you, no worries. However, seems (with current code) you will not be able to easily map "DB name"->"resource id", other than using ListDatabases call and filtering on client side

**Comment by ralbert05** [comment]
Thank you so much for the comments, you've been extremely helpful and I definitely would not have gotten it to work without you. I now am querying down to the document. Thank you.

One last question - do you know if this will compile nicely for Android/iOS? At a cursory glance I don't see why it shouldn't, but if you have any knowledge on this I would love to know! 
Cheers 👍

**Comment by stalker314314** [comment]
Awesome!:)

It _should_:) However, I must admit I didn't tried that since initial commit. Only thing that is worrisome is C++ REST SDK which [should work nicely](https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Android-on-Windows). That being said, I will gladly accept any document you write during your endeavor and put here, either as .md or wiki page!:)
